name: Commit Quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run

  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          working_dir: "src/usr/local/php/unraid-tailscale-utils"
      - run: "vendor/bin/phpstan"

  commitlint:
    name: Commitlint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install commitlint
        run: |
          npm install -g commitlint
          npm install -g "@commitlint/config-conventional"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
